#pragma once

#ifndef ETH_TX_ZERO_COPY_ENABLE
#define ETH_TX_ZERO_COPY_ENABLE 1
#endif

#ifndef ETH_RX_ZERO_COPY_ENABLE
#define ETH_RX_ZERO_COPY_ENABLE 0
#endif

#ifndef ETH_TX_COPY_FALLBACK_ENABLE
#define ETH_TX_COPY_FALLBACK_ENABLE 1
#endif

#ifndef ETH_TX_CHECKSUM_OFFLOAD_ENABLE
#define ETH_TX_CHECKSUM_OFFLOAD_ENABLE 1
#endif
